"""Initial migration

Revision ID: a06c774e3bf9
Revises: 
Create Date: 2025-12-04 13:42:29.348391

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a06c774e3bf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('radiant_team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dire_team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_provider_match_id'), 'match', ['provider_match_id'], unique=False)
    op.create_table('tick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('game_time', sa.Integer(), nullable=False),
    sa.Column('win_probability', sa.Float(), nullable=False),
    sa.Column('radiant_gold_lead', sa.Integer(), nullable=False),
    sa.Column('radiant_xp_lead', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tick_game_time'), 'tick', ['game_time'], unique=False)
    op.create_index(op.f('ix_tick_match_id'), 'tick', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tick_match_id'), table_name='tick')
    op.drop_index(op.f('ix_tick_game_time'), table_name='tick')
    op.drop_table('tick')
    op.drop_index(op.f('ix_match_provider_match_id'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###
